config/routes.rb
FormWizard::Application.routes.draw do
  devise_for :users
  resources :bunch_types
  resources :polls
  resources :companies
  resources :admins
  resources :main
  root to: 'main#index'
end

app/models/bunch_field.rb
class BunchField < ActiveRecord::Base
  belongs_to :bunch_type
  validates :name, presence: true
end

app/models/bunch_type.rb
class BunchType < ActiveRecord::Base
  validates :name, presence: true
  has_many :fields, class_name: "BunchField"
  has_many :polls
  accepts_nested_attributes_for :fields, allow_destroy: true

  default_scope { where(company_id: Company.current_id) }

  def self.names_bunch
    ["Contact Info", "Motivation letter", "Personal Info", "Job", "Accounts", "Extra uploads"]
  end
end

app/models/company.rb
class Company < ActiveRecord::Base
  after_create :create_bunches

  def create_bunches
    BunchType.names_bunch.each do |bunch_type|
      BunchType.create!(name: bunch_type, company_id: self.id)
    end
  end

  def self.current_id=(id)
    Thread.current[:company_id] = id
  end

  def self.current_id
    Thread.current[:company_id]
  end

  has_many :polls
  has_many :bunch_types
  has_many :users
end

app/models/poll.rb
class Poll < ActiveRecord::Base
  belongs_to :bunch_type
  serialize :properties, Hash

  validate :validate_properties

  default_scope { where(company_id: Company.current_id) }

  def validate_properties
    bunch_type.fields.each do |field|
      if field.required? && properties[field.name].blank?
        errors.add field.name, "must not be blank"
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  default_scope { where(company_id: [Company.current_id, nil])}

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :company
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  layout "admin"

  before_filter :authenticate_user!

  def index
    if current_user.admin
      redirect_to :controller=>'companies', :action => 'index'
    else
      @bunches = BunchType.all
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :scope_current_company, if: :not_controllers
  after_filter :store_location

  def not_controllers
    return false if self.controller_name == "companies" or self.controller_name == "main"
    true
  end

  def after_sign_in_path_for(resource)
    admins_path
  end

  private
  def store_location
    session[:return_to] = request.fullpath
  end

  def clear_stored_location
    session[:return_to] = nil
  end

  def redirect_back_or_to(alternate)
    redirect_to(session[:return_to] || alternate)
    clear_stored_location
  end

  protected

  def current_company
    Company.find_by_subdomain request.subdomain
  end
  helper_method :current_company

  def scope_current_company
    if current_company.blank?
      Company.current_id = nil
    else
      Company.current_id = current_company.id
    end
  end
end

app/controllers/bunch_types_controller.rb
class BunchTypesController < ApplicationController
  before_filter :authenticate_user!

  before_action :set_bunch_type, only: [:show, :edit, :update]

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @bunch_type.update(bunch_type_params)
        format.html { redirect_to :back, notice: 'Group form type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit'}
        format.json { render json: @bunch_type.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bunch_type
      @bunch_type = BunchType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bunch_type_params
      params.require(:bunch_type).permit(:name, :company_id, fields_attributes: [:id, :field_type, :name, :required])
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :is_admin?
  layout "company"

  def index
    @companies = Company.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  def show
    @company= Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  def new
    @company = Company.new
    respond_to do |format|
      format.html { render "companies/new" }
      format.json { render json: @company }
    end
  end

  def create
    p company_params
    @company = Company.new(company_params)
    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new_company" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

private
  def is_admin?
    redirect_to root_path unless current_user.admin
  end

  def company_params
    params.require(:company).permit(:name, :subdomain)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_filter :scope_current_company
  layout "main"
  def index
  end

private
  def current_company
    Company.find_by_subdomain request.subdomain
  end
  helper_method :current_company

  def scope_current_company
    if current_company.blank?
      Company.current_id = nil
    else
      Company.current_id = current_company.id
      redirect_to action: "new", controller: "polls", bunch_type_id: BunchType.first.id
    end
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_bunch, only: [:edit]

  def show
    @polls = Poll.where(bunch_type_id: params[:id])
  end

  def new
    @poll = Poll.new(bunch_type_id: params[:bunch_type_id])
  end

  def edit
  end

  def create
    @poll = Poll.new(poll_params)
    respond_to do |format|
      if @poll.save
        format.html { redirect_to :back, notice: 'Answer was successfully saved. Please go to next form' }
      else
        format.html { render action: 'new' }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bunch
      @poll = Poll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poll_params
      params.require(:poll).permit(:name, :company_id, :bunch_type_id).tap do |whitelisted|
        whitelisted[:properties] = params[:poll][:properties]
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields btn btn-info", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/bunch_types_helper.rb
module BunchTypesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/admins/index.html.erb
<h2>Your company name: <%= current_company.name%></h2>
<p>Your current forms for users apply:</p>
<div class="col-lg-offset-4">
    <% @bunches.each do |bunch| %>
      <div class="form_branch">
        <p>
          <strong>Name:</strong>
          <%= bunch.name %>
        </p>
        <%unless bunch.fields.blank?%>
            <% bunch.fields.each do |field|%>
                <p>Input: <label><%= field.name%></label></p>
            <%end%>
        <%end%>
        <%= link_to("Edit form", edit_bunch_type_path(bunch.id)) %>
      </div>
    <% end %>
</div>

app/views/bunch_types/_field_fields.html.erb
<fieldset>
  <%= f.select :field_type, %w[text_field check_box shirt_sizes text_area] %>
  <%= f.text_field :name, placeholder: "field_name" %>
  <%= f.check_box :required %> <%= f.label :required %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</fieldset>

app/views/bunch_types/_form.html.erb
<%= form_for(@bunch_type) do |f| %>
  <% if @bunch_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bunch_type.errors.count, "error") %> prohibited this form type from being saved:</h2>

      <ul>
      <% @bunch_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.fields_for :fields do |builder| %>
    <%= render 'field_fields', f: builder %>
  <% end %>
  <%= link_to_add_fields "Add Field", f, :fields%>

  <div class="actions">
    <%= f.submit "Save form",:class => 'btn btn-success' %>
  </div>
<% end %>

app/views/bunch_types/edit.html.erb
<h3>Form for <label><%= @bunch_type.name%></label></h3>

<%= render 'form' %>

app/views/bunch_types/index.html.erb
<h1>Listing group_types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bunch_types.each do |bunch_type| %>
      <tr>
        <td><%= bunch_type.name %></td>
        <td><%= link_to 'Show', bunch_type %></td>
        <td><%= link_to 'Edit', edit_bunch_type_path(bunch_type) %></td>
        <td><%= link_to 'Destroy', bunch_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group type', new_bunch_type_path %>

app/views/bunch_types/new.html.erb
<%= render 'form' %>

app/views/bunch_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bunch_type.name %>
</p>
<% @bunch_type.fields.each do |field|%>
    <p><%= field.name%></p>
<%end%>

app/views/companies/_form.html.erb
<%= form_for @company do |f|%>
    <%- if @company.errors.any?%>
        <div id="error_explanation">
            <h2><%= "#{pluralize(@company.errors.count, "error")} prohibited this company from being saved:"%></h2>
            <ul>
                <%- @company.errors.full_messages.each do |msg|%>
                    <li><%= msg%></li>
                <%end%>
            </ul>
        </div>
    <%end%>

    <div class="field">
        <%= f.label :name%>
        <%= f.text_field :name%>
    </div>
    <div class="field">
        <%= f.label :subdomain%>
        <%= f.text_field :subdomain%>
        <label>You need add this subdomain in you settings host</label>
    </div>
    <div class="actions">
        <%= f.submit 'Save', :class => "btn btn-primary"%>
    </div>
<%end%>

app/views/companies/index.html.erb
<% @companies.each do |company| %>
    <div class="poll">
      <h2><%= company.name %></h2>
    </div>
<% end %>
<%= link_to 'Create a new company', new_company_path, :class => "btn btn-primary btn-xs"%>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'companies/form'%>

app/views/companies/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>
<p>
  <strong>URL:</strong>
  <% url = root_url.to_s.split("://")%>
  <%= @company.subdomain %>.<%= url[1]%>
</p>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>FormWizard</title>
  <meta charset="utf-8">
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="navbar navbar-default navbar-fixed-top" role="banner">
  <div class="navbar-header">
    <%= link_to "The FormWizard",  root_path, :class=>"navbar-brand" %>
  </div>
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class ="nav navbar-nav">
      <li class="<%= 'active' if params[:controller] == "admins" && params[:action] == "index"%>"><%= link_to("Your current forms", admins_path) %></li>
      <%unless Poll.all.blank?%>
        <li class="<%= 'active' if params[:controller] == "polls" && params[:action] == "show"%>"><%= link_to("Your applies", poll_path(Poll.first.id)) %></li>
      <%end%>
    </ul>
    <ul class = "nav navbar-nav navbar-right">
      <li>
        <%- if user_signed_in?%>
            <%= link_to 'Sign out', destroy_user_session_path, :method => :delete, :class=>"btn btn-li btn-danger"%>
        <%end%>
      </li>
    </ul>
  </div>
</header>
<div id="container"  style="margin-top: 7%">
  <% flash.each do |name, msg| %>
      <br>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
  <% end %>
  <%= yield %>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>FormWizard</title>
  <meta charset="utf-8">
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="navbar navbar-default navbar-fixed-top" role="banner">
  <div class="navbar-header">
    <%= link_to "The FormWizard",  root_path, :class=>"navbar-brand" %>
  </div>
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class ="nav navbar-nav">
      <%if params[:controller] == "bunch_types" || (params[:controller] == "polls" && params[:action] == "show" )%>
        <li class="<%= 'active' if params[:controller] == "admins" && params[:action] == "index"%>"><%= link_to("Your current forms", admins_path) %></li>
        <%if !Poll.all.blank? and params[:controller] == "polls"%>
          <li class="<%= 'active' if params[:controller] == "polls" && params[:action] == "show"%>"><%= link_to("Your applies", poll_path(Poll.first.id)) %></li>
        <%end%>
      <%end%>
    </ul>
    <ul class = "nav navbar-nav navbar-right">
      <li>
        <%- if user_signed_in?%>
            <%= link_to 'Sign out', destroy_user_session_path, :method => :delete, :class=>"btn btn-li btn-danger"%>
        <%end%>
      </li>
    </ul>
  </div>
</header>
<div id="container">
  <div class="bootstrap">
    <div class="navbar">
      <div class="navbar-inner">
        <div class="container">
          <ul class="nav nav-pills">
            <%- if params[:controller] == "bunch_types"%>
                <%BunchType.order("id").all.each do |bunch|%>
                    <li class="<%= 'active' if current_page?(edit_bunch_type_path("#{bunch.id}")) %>"><%= link_to("#{bunch.name}", edit_bunch_type_path(bunch.id)) %></li>
                <%end%>
            <%- elsif params[:controller] == "polls" && params[:action] == "show" %>
                <%BunchType.order("id").all.each do |bunch|%>
                    <li class="<%= 'active' if current_page?(poll_path("#{bunch.id}")) %>"><%= link_to("#{bunch.name}", poll_path(bunch.id)) %></li>
                <%end%>
            <%-else%>
                <%BunchType.order("id").all.each do |bunch|%>
                    <li class="<%= 'active' if current_page?(new_poll_path(bunch_type_id: "#{bunch.id}")) %>"><%= link_to("#{bunch.name}", (new_poll_path(bunch_type_id: "#{bunch.id}"))) %></li>
                <%end%>
            <%- end%>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
  <% end %>
  <%= yield %>
</div>
</body>
</html>

app/views/layouts/company.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>FormWizard</title>
  <meta charset="utf-8">
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="navbar navbar-default navbar-fixed-top" role="banner">
  <div class="navbar-header">
    <%= link_to "The FormWizard",  root_path, :class=>"navbar-brand" %>
  </div>
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class ="nav navbar-nav">
      <li class="<%= 'active' if params[:controller] == "companies" && params[:action] == "index"%>"><%= link_to("List of companies", companies_path) %></li>
      <li class="<%= 'active' if params[:controller] == "companies"  && params[:action] != "index"%>"><%= link_to("New company", new_company_path) %></li>
    </ul>
    <ul class = "nav navbar-nav navbar-right">
      <li>
        <%- if user_signed_in?%>
            <%= link_to 'Sign out', destroy_user_session_path, :method => :delete, :class=>"btn btn-li btn-danger"%>
        <%end%>
      </li>
    </ul>
  </div>
</header>
<div id="container"  style="margin-top: 7%">
  <% flash.each do |name, msg| %>
      <br>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
  <% end %>
  <%= yield %>
</div>
</body>
</html>

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>FormWizard</title>
  <meta charset="utf-8">
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="navbar navbar-default navbar-fixed-top" role="banner">
  <div class="navbar-header">
    <%= link_to "The FormWizard",  root_path, :class=>"navbar-brand" %>
  </div>
</header>
<div id="container" style="margin-top: 7%">
  <% flash.each do |name, msg| %>
      <br>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
  <% end %>
  <%= yield %>
</div>
</body>
</html>

app/views/main/index.html.erb
<p>
  This is a Multi-tennant Platform. It will handle your users invitations. It is meant as a platform for your apps that allow users of a company or organization to easily create apply forms.
  Please contact to us at email aaa@ggg.com
</p>

app/views/polls/_form.html.erb
<%= form_for(@poll) do |f| %>
  <% if @poll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poll.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @poll.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :bunch_type_id %>

  <%= f.fields_for :properties, OpenStruct.new(@poll.properties) do |builder| %>
    <% @poll.bunch_type.fields.each do |field| %>
      <%= render "polls/fields/#{field.field_type}", field: field, f: builder %>
    <% end %>
  <% end %>

  <%- unless @poll.bunch_type.fields.empty?%>
    <div class="actions">
      <%= f.submit "Save answers",:class => 'btn btn-success' %>
    </div>
  <%end%>
<% end %>

app/views/polls/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @poll %> |
<%= link_to 'Back', polls_path %>

app/views/polls/fields/_check_box.html.erb
<div class="field">
  <%= f.check_box field.name %>
  <%= f.label field.name %>
</div>

app/views/polls/fields/_shirt_sizes.html.erb
<div class="field">
  <%= f.label field.name %><br />
  <%= f.select field.name, %w[S M L XL], {}, {multiple: true} %>
</div>

app/views/polls/fields/_text_area.html.erb
<div class="field">
  <%= f.label field.name %><br />
  <%= f.text_area field.name %>
</div>

app/views/polls/fields/_text_field.html.erb
<div class="field">
  <%= f.label field.name %><br />
  <%= f.text_field field.name %>
</div>

app/views/polls/index.html.erb
<h1>Store</h1>

<% if @polls.empty? %>
    <p><strong>No answers</strong></p>
<% end %>

<% @polls.each do |poll| %>
    <div class="poll">
      <h2><%= poll.name %></h2>
    </div>
<% end %>

<%= form_tag new_poll_path, method: :get do %>
    <%= select_tag :bunch_type_id, options_from_collection_for_select(BunchType.all, :id, :name) %>
    <%= submit_tag "New Group", name: nil %>
<% end %>

app/views/polls/new.html.erb
<h3>Please complete next form:</h3>

<%= render 'form' %>

app/views/polls/show.html.erb
<%- unless @polls.blank?%>
  <p>
    Answers for form:
    <label><%= @polls.first.bunch_type.name %></label>
  </p>

  <%- @polls.each do |poll|%>
    <p><b>Date:</b>
      <%= poll.created_at%>
    </p>
    <% poll.properties.each do |name, value| %>
      <p>
        <b><%= name.humanize %>:</b>
        <%= value %>
      </p>
    <% end %>
    <br>
  <% end %>
<%end%>